### PR TITLE
Make it work

### PR DESCRIPTION
**Pull request by Yuhta**

### CODE REVIEW

**Comment by pwoolcoc** [comment]
Hey, thanks! I was just thinking this weekend that I needed to get back to this. I feel a bit disingenuous having my name in the "authors" field, as all I did was `cargo new`, so would you like to take ownership of this? I can see about transferring the repo to you, as well as ownership of the crate on `crates.io`.

**Comment by Yuhta** [comment]
Hi @pwoolcoc , yes you can transfer this repo as well as the crate to me.  Thanks!

**Comment by pwoolcoc** [comment]
Looks like I can't transfer this repo to you unless you delete your fork, so I guess it is up to you..I will get the crate ownership transferred to you, and you could just add the URL to your fork to the `repository =` key in the Cargo.toml.

**Comment by pwoolcoc** [comment]
ok, I added you as an owner of the crate on crates.io. I removed myself from the `authors=` key, go ahead and remove me as an owner, if you wish (`cargo owner --remove pwoolcoc`).

**Comment by Yuhta** [comment]
Hi @pwoolcoc , I deleted my fork and you can do the transfer now.

**Pull request merged**
